# This file is used to install packages used by the Streamlit App.
# For more details, refer to https://docs.snowflake.com/en/developer-guide/streamlit/create-streamlit-sql#label-streamlit-install-packages-manual

channels:
- snowflake
dependencies:
- snowflake-native-apps-permission
- streamlit=1.26.0
- snowflake-ml-python
# - geopandas
# - streamlit-folium
# - plotly
- altair
