def get_label(key: str, lang: str):
    en_labels = {
        "key_title": "Google Analytics 4-Snowflake Dashboard",
        "key_select_period": "Select period to aggregate.",
        "key_select_oprion_suffix": "days",
        "key_user_count": "Users",
        "key_event_count": "Events",
        "key_new_user_count": "New Users",
        "key_graph_title_page_title_count": "Page views TOP10",
        "key_graph_device_model_count": "Terminals used by users TOP10",
        "key_graph_title_device_os_ver_count": "Terminal OS version used by user TOP10",
        "key_graph_title_user_event_count": "Events",
        "key_graph_title_user_traffic_count": "User traffic",
        "key_graph_title_user_region_count": "Access users by region TOP10",
        "key_graph_label_format_month-day": "%m-%d",
        "key_filter_option_title": "filter",
        "key_filter_option_all_users": "all users",
        "key_filter_option_new_users": "new users",
        "key_loading_label": "Loading…",
        "key_load_error": 'Click on the Security tab and grant access to the view imported using the "Snowflake Connector for Google Analytics Raw Data" (e.g., ANALYTICS_〇〇〇〇〇〇〇〇_VIEW)."',
        "key_SQL_error": "The SQL you executed is incorrect. Try changing the question.",
        "key_expander_label": "🤖 Analyzed by Snowflake Arctic",
        "key_text_input_label": "Please enter your question",
        "key_button_regeneration_label": "Regeneration",
        "key_button_cdv_dl_label": "📥 Download CSV",
        "key_button_display_df_label": "Execute SQL to display data frame",
        "key_graph_title_actual": "###### Actual data",
        "key_graph_title_forecast": "###### Predicted Data",
        "key_llm_error": "Snowflake Arctic may not be an available region or the maximum number of tokens has been exceeded.",
        "key_forecast_data_load_error": "Click on the Security tab and allow access to the forecast data",
    }
    ja_labels = {
        "key_title": "Google Analytics 4-Snowflakeダッシュボード",
        "key_select_period": "集計期間を選択してください。",
        "key_select_oprion_suffix": "日間",
        "key_user_count": "ユーザー数",
        "key_event_count": "イベント数",
        "key_new_user_count": "新規ユーザー数",
        "key_graph_title_page_title_count": "ページ閲覧数 TOP10",
        "key_graph_device_model_count": "使用端末 TOP10",
        "key_graph_title_device_os_ver_count": "使用端末OSバージョン TOP10",
        "key_graph_title_user_event_count": "イベント数",
        "key_graph_title_user_traffic_count": "ユーザーのトラフィック",
        "key_graph_title_user_region_count": "地域別アクセスユーザー TOP10",
        "key_graph_label_format_month-day": "%m月%d日",
        "key_filter_option_title": "絞り込む",
        "key_filter_option_all_users": "全ユーザー",
        "key_filter_option_new_users": "新規ユーザー",
        "key_loading_label": "読込中…",
        "key_load_error": "セキュリティタブをクリックし、「Snowflake Connector for Google Analytics Raw Data」を使って取り込んだビュー(例：ANALYTICS_123456789_VIEW)へのアクセスを許可してください",
        "key_SQL_error": "実行したSQLが正しくありません。質問文を変更してみて下さい。",
        "key_expander_label": "🤖 Snowflake Arcticで分析",
        "key_text_input_label": "質問内容を入力してください",
        "key_button_regeneration_label": "再生成",
        "key_button_cdv_dl_label": "📥 CSVでダウンロード",
        "key_button_display_df_label": "SQLを実行してデータフレームを表示",
        "key_graph_title_actual": "###### 実測データ",
        "key_graph_title_forecast": "###### 予測データ",
        "key_llm_error": "Snowflake Arcticの利用可能リージョンではないか、トークン数の上限を超えた可能性があります。",
        "key_forecast_data_load_error": "セキュリティタブをクリックし、予測データへのアクセスを許可してください",
    }

    if lang == "日本語":
        return ja_labels[key]
    else:
        return en_labels[key]
